server:
  port: 8000

eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring: 
  jpa: 
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    database: POSTGRESQL 
    show-sql: false 
    hibernate: 
      ddl-auto: create-drop 
  datasource: 
    platform: postgres 
    url: jdbc:postgresql://localhost:5432/zeus 
    username: postgres 
    password: YhjPVFam5pGDhM8Bdxh2frfss8ZGJa 
    driverClassName: org.postgresql.Driver
    initialization: 
      mode: always
  jackson:
    time-zone: America/Campo_Grande